# Generated by Django 2.2.7 on 2019-11-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191123_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.CharField(default='this is cool', max_length=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(default='this is cool'),
        ),
    ]
